FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app
COPY . .

WORKDIR /app/API_Automation

RUN dotnet restore
RUN dotnet build -c Release

ENTRYPOINT ["dotnet", "test", "API_Automation.csproj", "-c", "Release"]
