// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace UI_Automation.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Copy and paste")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("regression")]
    [global::NUnit.Framework.CategoryAttribute("allure.epic:SteamWebInterface")]
    [global::NUnit.Framework.CategoryAttribute("allure.feature:CopyPaste")]
    [global::NUnit.Framework.CategoryAttribute("allure.owner:Srdjan_Miljus")]
    [global::NUnit.Framework.CategoryAttribute("allure.severity:critical")]
    public partial class CopyAndPasteFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "regression",
                "allure.epic:SteamWebInterface",
                "allure.feature:CopyPaste",
                "allure.owner:Srdjan_Miljus",
                "allure.severity:critical"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Copy and paste", "  As a user\r\n  I want to search for game and navigate to the official Steam About" +
                " page\r\n  So that I can play games on the Steam platform", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CopyAndPaste.feature.ndjson", 5);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Copy")]
        [global::NUnit.Framework.CategoryAttribute("ui")]
        public async global::System.Threading.Tasks.Task Copy()
        {
            string[] tagsOfScenario = new string[] {
                    "ui"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Copy", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I open Store page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I search for \"FIFA\" game", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("I should see the first search result \"EA SPORTS FC™ 25\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("I should see the second search result \"FIFA 22\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I search for \"THE FINALS\" game", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.AndAsync("I click on the first search result in the search results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.ThenAsync("I should be redirected to the \"THE_FINALS\" page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("I should see the game name \"THE FINALS\" from the 1st search result", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I click on Play Game button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.AndAsync("I click on No, I need Steam button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.ThenAsync("I should be redirected to the \"about\" page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("I should see the Install Steam button is clickable", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("I should see that Playing Now gamers status are less than Online gamers status", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Paste")]
        [global::NUnit.Framework.CategoryAttribute("ui")]
        public async global::System.Threading.Tasks.Task Paste()
        {
            string[] tagsOfScenario = new string[] {
                    "ui"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Paste", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I open Store page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I search for \"THE FINALS\" game", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.AndAsync("I click on the first search result in the search results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.ThenAsync("I should be redirected to the \"THE_FINALS\" page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("I should see the game name \"THE FINALS\" from the 1st search result", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I click on Play Game button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.AndAsync("I click on No, I need Steam button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.ThenAsync("I should be redirected to the \"about\" page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("I should see the Install Steam button is clickable", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("I should see that Playing Now gamers status are less than Online gamers status", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Cut")]
        [global::NUnit.Framework.CategoryAttribute("ui")]
        public async global::System.Threading.Tasks.Task Cut()
        {
            string[] tagsOfScenario = new string[] {
                    "ui"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cut", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I open Store page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.WhenAsync("I search for \"THE FINALS\" game", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.AndAsync("I click on the first search result in the search results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.ThenAsync("I should be redirected to the \"THE_FINALS\" page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("I should see the game name \"THE FINALS\" from the 1st search result", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I click on Play Game button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
